### ISSUE TITLE
update bundled proj to 9.0.0

### ISSUE THREAD

**Issue by michaelkirk** [georust/proj#96]
Do you mind if I work on updating proj to 8.2?

In particular there are some failing test cases on aarch64 that go away after the update.

**Comment by urschrei** [comment]
No, go for it! (I will get back to you re: opaque pointers…)

**Comment by michaelkirk** [comment]
I ended up getting hamstrung with the 8.2 release by https://github.com/georust/proj/pull/104.

That eventually got fixed. I finally found some time and went to complete the 8.2 update only to find that proj 9.0.0 has been released in the meanwhile, so I'm now working on updating to that. 🙇

**Comment by urschrei** [comment]
Amazing, thank you. I don't know whether you're on the PROJ mailing list, but the release cadence (bug fixes notwithstanding) is slowing down by design for now:


9.0.1: June 8th 2022
9.1.0: September 1st 2022
9.1.1: December 1st 2022
9.2.0: March 1st 2023

So we have a bit more time between releases if the 9.0 upgrade goes smoothly.
